# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""The hosts and subnets an operator has banned, Core's `BanMan`.

`BanMan` is Core's class of the same name (`src/banman.cpp`), `Subnet`
its `CSubNet` (`src/netaddress.cpp`) and `lookup_subnet` its
`LookupSubNet` (`src/netbase.cpp`), all read at bitcoin/bitcoin@9be056a8a7,
the v31.1 tag. The list is kept in `banlist.json` in Core's own format
(`src/addrdb.cpp`, `src/net_types.cpp`), so either node reads the
other's.

A subnet here is an IPv4 or an IPv6 one: an onion, I2P or CJDNS address,
which Core bans as a single host, is refused as unparsable
(btclib-org/btclib-node#1218).
"""

import json
import threading
import time
from dataclasses import dataclass
from ipaddress import IPv4Address, IPv6Address, ip_address
from typing import TYPE_CHECKING, Any, override

from btclib.p2p.addrv2 import can_addrv1, network_address

from btclib_node.constants import CLIENT_NAME
from btclib_node.p2p.eviction import _INTERNAL, _TORV2, is_valid

if TYPE_CHECKING:
    import logging
    from pathlib import Path

    from btclib.p2p.addrv2 import NetworkAddressV2

__all__ = [
    "DEFAULT_MISBEHAVING_BANTIME",
    "DUMP_BANS_INTERVAL",
    "BanEntry",
    "BanMan",
    "Subnet",
    "is_valid_host",
    "lookup_host",
    "lookup_subnet",
]

# Core's `-bantime` default, which this node has no option to override
# (btclib-org/btclib-node#1219)
DEFAULT_MISBEHAVING_BANTIME = 60 * 60 * 24
# How often Core's scheduler calls `DumpBanlist`, in seconds
DUMP_BANS_INTERVAL = 15 * 60

# `CBanEntry::CURRENT_VERSION`, and the keys `CBanDB` and `WriteSettings`
# write
_BAN_ENTRY_VERSION = 1
# the first integer past `int64_t`
_INT64_END = 1 << 63
_JSON_KEY = "banned_nets"
_WARNING_KEY = "_warning_"
_WARNING = (
    f"This file is automatically generated and updated by {CLIENT_NAME}. "
    "Please do not edit this file while the node is running, as any changes "
    "might be ignored or overwritten."
)


def lookup_host(text: str) -> IPv4Address | IPv6Address | None:
    """Core's `LookupHost` without DNS, for an IP address alone.

    Brackets around the address are stripped. An IPv4 address mapped
    into IPv6 is IPv4, an address under Core's internal prefix is
    refused, and one under the Tor v2 prefix is the unspecified address,
    as `CNetAddr::SetLegacyIPv6` reads them. What `getaddrinfo` accepts
    and `ipaddress` does not, such as `1.2.3` or a scope id, is refused
    (btclib-org/btclib-node#1220).
    """
    if text.startswith("[") and text.endswith("]"):
        text = text[1:-1]
    try:
        ip = ip_address(text) if "%" not in text else None
    except ValueError:
        ip = None
    if isinstance(ip, IPv6Address):
        if ip.ipv4_mapped is not None:
            ip = ip.ipv4_mapped
        elif ip in _INTERNAL:
            ip = None
        elif ip in _TORV2:
            ip = IPv6Address(0)
    return ip


def _mapped(ip: IPv4Address | IPv6Address) -> IPv6Address:
    """Return `ip` as the sixteen octets `is_valid` reads."""
    if isinstance(ip, IPv4Address):
        return IPv6Address(b"\x00" * 10 + b"\xff\xff" + ip.packed)
    return ip


def is_valid_host(ip: IPv4Address | IPv6Address) -> bool:
    """Core's `CNetAddr::IsValid` of an IP address `lookup_host` gave."""
    return is_valid(_mapped(ip))


@dataclass(frozen=True)
class Subnet:
    """Core's `CSubNet` of an IP network: a network and its prefix length.

    `network` is already masked. `sort_key` orders them as Core's
    `std::map` of them does, IPv4 ahead of IPv6.
    """

    network: IPv4Address | IPv6Address
    prefix: int

    @classmethod
    def of(cls, ip: IPv4Address | IPv6Address, prefix: int | None = None) -> Subnet:
        """Return the `prefix`-bit subnet holding `ip`, `ip` alone if none."""
        if prefix is None:
            prefix = ip.max_prefixlen
        mask = _mask(ip.max_prefixlen, prefix)
        return cls(type(ip)(int(ip) & mask), prefix)

    def sort_key(self) -> tuple[int, bytes, int]:
        """Core's `operator<` of two `CSubNet`: kind, octets, then netmask."""
        return (self.network.version, self.network.packed, self.prefix)

    def matches(self, ip: IPv4Address | IPv6Address) -> bool:
        """Core's `CSubNet::Match` of a valid address."""
        if ip.version != self.network.version or not is_valid_host(ip):
            return False
        return int(ip) & _mask(ip.max_prefixlen, self.prefix) == int(self.network)

    def matches_peer(self, address: NetworkAddressV2) -> bool:
        """Answer `matches` of a peer's address, false off the IP networks."""
        ip = _peer_ip(address)
        return ip is not None and self.matches(ip)

    @override
    def __str__(self) -> str:
        """Core's `CSubNet::ToString`: the network, a slash and the prefix."""
        return f"{self.network}/{self.prefix}"


def _mask(bits: int, prefix: int) -> int:
    return ((1 << prefix) - 1) << (bits - prefix)


def _prefix(mask: IPv4Address | IPv6Address) -> int | None:
    """Return a netmask's prefix length, `None` where it is not contiguous."""
    inverted = ~int(mask) & ((1 << mask.max_prefixlen) - 1)
    if inverted & (inverted + 1):
        return None
    return mask.max_prefixlen - inverted.bit_length()


def lookup_subnet(text: str) -> Subnet | None:
    """Core's `LookupSubNet`: an address, then a CIDR prefix or a netmask.

    Split at the last slash. A suffix of decimal digits up to 255 is a
    prefix length, valid up to the address's own; anything else is read
    as a netmask of the same kind, which has to be contiguous. With no
    slash the subnet is the one host.
    """
    slash = text.rfind("/")
    ip = lookup_host(text if slash < 0 else text[:slash])
    if ip is None:
        return None
    if slash < 0:
        return Subnet.of(ip)
    suffix = text[slash + 1 :]
    # `ToIntegral<uint8_t>`: ASCII digits alone, and at most 255
    if suffix.isascii() and suffix.isdigit() and int(suffix) <= 0xFF:  # noqa: PLR2004
        prefix = int(suffix)
        return Subnet.of(ip, prefix) if prefix <= ip.max_prefixlen else None
    mask = lookup_host(suffix)
    if mask is None or mask.version != ip.version:
        return None
    prefix_of_mask = _prefix(mask)
    return None if prefix_of_mask is None else Subnet.of(ip, prefix_of_mask)


def _peer_ip(address: NetworkAddressV2) -> IPv4Address | IPv6Address | None:
    """Return a peer's IP, IPv4 where mapped, `None` for any other network."""
    if not can_addrv1(address):
        return None
    ip = network_address(address).ip
    return ip.ipv4_mapped or ip


@dataclass(frozen=True)
class BanEntry:
    """Core's `CBanEntry`: when the ban was set, and until when it holds."""

    create_time: int
    ban_until: int


class _BanlistError(ValueError):
    """`banlist.json` is not what `CBanDB::Read` accepts."""


class _JsonObject(list[tuple[str, Any]]):
    """A JSON object as UniValue holds one: its pairs, duplicates kept."""

    def get(self, key: str) -> Any:  # noqa: ANN401
        """UniValue's `operator[]`: the first value under `key`."""
        return next((value for k, value in self if k == key), None)


def _json_int(entry: _JsonObject, key: str, bits: int) -> int:
    """UniValue's `getInt` of `entry[key]`: an integer within `bits` signed."""
    value = entry.get(key)
    if type(value) is not int or not -(1 << (bits - 1)) <= value < 1 << (bits - 1):
        raise _BanlistError(key)
    return value


def _now() -> int:
    """Core's `GetTime()`: whole seconds since the epoch."""
    return int(time.time())


class BanMan:
    """Core's `BanMan`, without the discouragement filter.

    `P2pManager.discourage` keeps that filter. Every method takes the
    lock Core's `m_banned_mutex` is, the RPC reaching this list on
    `Node`'s thread and the accept and dial paths on `P2pManager`'s.
    `path` `None` keeps the list in memory only.
    """

    def __init__(
        self,
        path: Path | None,
        logger: logging.Logger,
        default_ban_time: int = DEFAULT_MISBEHAVING_BANTIME,
    ) -> None:
        """Load the list, then write it back, as Core's constructor does."""
        self.path = path
        self.logger = logger
        self.default_ban_time = default_ban_time
        self._banned: dict[Subnet, BanEntry] = {}
        self._lock = threading.Lock()
        self._dump_lock = threading.Lock()
        self._dirty = False
        self._load()
        self.dump()

    def _load(self) -> None:
        """Core's `LoadBanlist`: a file it cannot read is recreated empty."""
        if self.path is None:
            return
        try:
            banned = self._read(self.path)
        except (OSError, UnicodeDecodeError, ValueError) as error:
            if not isinstance(error, FileNotFoundError):
                self.logger.warning("Cannot load banlist %s: %s", self.path, error)
            self.logger.info("Recreating the banlist database")
            with self._lock:
                self._dirty = True
            return
        with self._lock:
            self._banned = banned
            self._sweep()

    def _read(self, path: Path) -> dict[Subnet, BanEntry]:
        """Core's `CBanDB::Read` and `BanMapFromJson`."""
        settings = json.loads(
            path.read_text(encoding="utf-8"), object_pairs_hook=_JsonObject
        )
        if not isinstance(settings, _JsonObject):
            raise _BanlistError(path)
        # `ReadSettings` refuses a top-level key the file holds twice
        keys = [key for key, _ in settings]
        if len(set(keys)) != len(keys):
            raise _BanlistError(keys)
        entries = settings.get(_JSON_KEY)
        # UniValue's `getValues` answers an object's values as well as
        # an array's, and throws for anything else
        if isinstance(entries, _JsonObject):
            entries = [value for _, value in entries]
        elif not isinstance(entries, list):
            raise _BanlistError(_JSON_KEY)
        banned: dict[Subnet, BanEntry] = {}
        for entry in entries:
            if not isinstance(entry, _JsonObject):
                raise _BanlistError(entry)
            version = _json_int(entry, "version", 32)
            if version != _BAN_ENTRY_VERSION:
                self.logger.info(
                    "Dropping entry with unknown version (%s) from ban list", version
                )
                continue
            address = entry.get("address")
            if not isinstance(address, str):
                raise _BanlistError(address)
            subnet = lookup_subnet(address)
            if subnet is None:
                self.logger.info(
                    "Dropping entry with unparsable address or subnet (%s)"
                    " from ban list",
                    address,
                )
                continue
            banned[subnet] = BanEntry(
                _json_int(entry, "ban_created", 64),
                _json_int(entry, "banned_until", 64),
            )
        return banned

    def dump(self) -> None:
        """Core's `DumpBanlist`: sweep, then write the list if it changed."""
        with self._dump_lock:
            with self._lock:
                self._sweep()
                if not self._dirty:
                    return
                banned = self._sorted()
                self._dirty = False
            if self.path is None:
                return
            document = {
                _WARNING_KEY: _WARNING,
                _JSON_KEY: [
                    {
                        "version": _BAN_ENTRY_VERSION,
                        "ban_created": entry.create_time,
                        "banned_until": entry.ban_until,
                        "address": str(subnet),
                    }
                    for subnet, entry in banned
                ],
            }
            try:
                self.path.write_text(
                    json.dumps(document, indent=4) + "\n", encoding="utf-8"
                )
            except OSError as error:
                self.logger.error("%s", error)  # noqa: TRY400
                with self._lock:
                    self._dirty = True

    def _sorted(self) -> list[tuple[Subnet, BanEntry]]:
        return sorted(self._banned.items(), key=lambda item: item[0].sort_key())

    def _sweep(self) -> None:
        """Core's `SweepBanned`: forget every ban already past its end."""
        now = _now()
        for subnet, entry in list(self._banned.items()):
            if now > entry.ban_until:
                del self._banned[subnet]
                self._dirty = True
                self.logger.debug("Removed banned node address/subnet: %s", subnet)

    def ban(
        self, subnet: Subnet, ban_time_offset: int = 0, *, absolute: bool = False
    ) -> None:
        """Core's `Ban`: for `ban_time_offset` seconds, or until it if absolute.

        An offset of zero or less is the default ban time from now. A
        ban already held is replaced only by one that ends later.
        """
        now = _now()
        if ban_time_offset <= 0:
            ban_time_offset = self.default_ban_time
            absolute = False
        # Core adds in `int64_t`, and bitcoind v31.1.0 wraps a sum past its
        # maximum to a negative end, which never beats the zero
        # `m_banned[sub_net]` default-constructs: the ban is not taken, and
        # `banlist.json` holds no end it cannot read back.
        until = (0 if absolute else now) + ban_time_offset
        entry = BanEntry(now, (until + _INT64_END) % (2 * _INT64_END) - _INT64_END)
        with self._lock:
            held = self._banned.get(subnet)
            if (0 if held is None else held.ban_until) >= entry.ban_until:
                return
            self._banned[subnet] = entry
            self._dirty = True
        self.dump()

    def unban(self, subnet: Subnet) -> bool:
        """Core's `Unban`: whether `subnet` was on the list to remove."""
        with self._lock:
            if self._banned.pop(subnet, None) is None:
                return False
            self._dirty = True
        self.dump()
        return True

    def clear(self) -> None:
        """Core's `ClearBanned`."""
        with self._lock:
            self._banned.clear()
            self._dirty = True
        self.dump()

    def is_banned(self, ip: IPv4Address | IPv6Address) -> bool:
        """Core's `IsBanned` of an address: any unexpired ban matching it."""
        now = _now()
        with self._lock:
            return any(
                now < entry.ban_until and subnet.matches(ip)
                for subnet, entry in self._banned.items()
            )

    def is_peer_banned(self, address: NetworkAddressV2) -> bool:
        """`is_banned` of a peer's address, never true off the IP networks."""
        ip = _peer_ip(address)
        return ip is not None and self.is_banned(ip)

    def is_subnet_banned(self, subnet: Subnet) -> bool:
        """Core's `IsBanned` of a subnet: that very subnet, unexpired."""
        now = _now()
        with self._lock:
            entry = self._banned.get(subnet)
            return entry is not None and now < entry.ban_until

    def banned(self) -> list[tuple[Subnet, BanEntry]]:
        """Core's `GetBanned`: swept first, in the list's own order."""
        with self._lock:
            self._sweep()
            return self._sorted()
