# Copyright (c) The btclib developers
# Distributed under the MIT software license, see the accompanying
# LICENSE file or https://opensource.org/license/mit for the full text.

"""`settings_file.py`: Core's UniValue reader and writer, and `settings.json`.

Every accepted and refused text below was run through `bitcoind` v31.1.0
(`-regtest -help`, which reads and writes the file and exits), and each
file written was compared byte for byte.
"""

import os
import sys
from typing import TYPE_CHECKING

import pytest

from btclib_node.constants import CLIENT_NAME
from btclib_node.settings_file import (
    Number,
    Object,
    read_settings,
    type_name,
    write_json,
    write_settings,
)

if TYPE_CHECKING:
    from pathlib import Path
    from typing import Self

    from btclib_node.settings_file import Json

_INVALID = "does not contain valid JSON. This may be caused by a crash"
_WARNING = (
    f"This file is automatically generated and updated by {CLIENT_NAME}. "
    "Please do not edit this file while the node is running, as any changes "
    "might be ignored or overwritten."
)


def _read(tmp_path: Path, content: str | bytes) -> dict[str, Json]:
    path = tmp_path / "settings.json"
    path.write_bytes(content.encode() if isinstance(content, str) else content)
    return read_settings(str(path))


def _refusal(tmp_path: Path, content: str | bytes) -> str:
    with pytest.raises(ValueError, match=r".") as refused:
        _read(tmp_path, content)
    # Core prints the path as the platform spells it, `\` on Windows.
    return str(refused.value).replace(str(tmp_path / "settings.json"), "<FILE>")


def _written(tmp_path: Path, content: str | bytes) -> str:
    """Return what `content` is written back as: Core's `-help` run."""
    path = tmp_path / "settings.json"
    write_settings(str(path), _read(tmp_path, content))
    return path.read_bytes().decode("utf-8")


def _file(*lines: str) -> str:
    """Return a settings file under the `_warning_` key, `lines` after it.

    Its line ends are the platform's, as the file is written in text mode.
    """
    warning = f'    "_warning_": "{_WARNING}"'
    body = ",\n".join([warning, *lines])
    return ("{\n" + body + "\n}\n").replace("\n", os.linesep)


@pytest.mark.parametrize(
    ("content", "expected"),
    [
        pytest.param("{}", _file(), id="empty object"),
        pytest.param(" \n{ }\t\r\n", _file(), id="whitespace"),
        pytest.param('{"a":1}', _file('    "a": 1'), id="number"),
        pytest.param('{"b":1,"a":2}', _file('    "a": 2', '    "b": 1'), id="sorted"),
        pytest.param(
            '{"B":3,"a":2,"é":4,"z":6,"~":8}',
            _file('    "B": 3', '    "a": 2', '    "z": 6', '    "~": 8', '    "é": 4'),
            id="key order is by code point",
        ),
        pytest.param(
            '{"_warning_":"mine","a":1}', _file('    "a": 1'), id="warning replaced"
        ),
        pytest.param(
            '{"a":1.50,"b":1E+2,"c":-0,"d":100000000000000000000000,"e":-0.0}',
            _file(
                '    "a": 1.50',
                '    "b": 1E+2',
                '    "c": -0',
                '    "d": 100000000000000000000000',
                '    "e": -0.0',
            ),
            id="numbers keep their text",
        ),
        pytest.param(
            '{"a":true,"b":false,"c":null}',
            _file('    "a": true', '    "b": false', '    "c": null'),
            id="literals",
        ),
        pytest.param(
            '{"a":[],"b":{},"c":[[],{}]}',
            _file(
                '    "a": [\n    ]',
                '    "b": {\n    }',
                '    "c": [\n        [\n        ],\n        {\n        }\n    ]',
            ),
            id="empty containers keep their line break",
        ),
        pytest.param(
            '{"a":[1,[2,{"d":null}]]}',
            _file(
                '    "a": [\n        1,\n        [\n            2,\n'
                '            {\n                "d": null\n            }\n'
                "        ]\n    ]"
            ),
            id="nesting",
        ),
        pytest.param(
            '{"a":{"z":1,"b":2}}',
            _file('    "a": {\n        "z": 1,\n        "b": 2\n    }'),
            id="nested keys keep file order",
        ),
        pytest.param(
            '{"a":{"x":1,"x":2}}',
            _file('    "a": {\n        "x": 1,\n        "x": 2\n    }'),
            id="a nested repeated key is kept",
        ),
        pytest.param(
            '{"a":"\\"\\\\\\/\\b\\f\\n\\r\\t\\u0001\\u007f\\u001f"}',
            _file('    "a": "\\"\\\\/\\b\\f\\n\\r\\t\\u0001\\u007f\\u001f"'),
            id="escapes",
        ),
        pytest.param(
            '{"a":"\\u00e9\\ud83d\\ude00\\u2028é"}',
            _file('    "a": "é\U0001f600\u2028é"'),
            id="escaped and raw unicode written raw",
        ),
        pytest.param(
            '{"\\u0000":"\\u0000","a/b":"c/d"}',
            _file('    "\\u0000": "\\u0000"', '    "a/b": "c/d"'),
            id="NUL and slash",
        ),
        pytest.param(
            '{"a":"\\ud800x\\udc00"}',
            _file('    "a": "x\U00010000"'),
            id="a first half and its second half, ASCII between",
        ),
        pytest.param('{\r\n"a":1\r\n}\r\n', _file('    "a": 1'), id="CRLF"),
        pytest.param('{"a":"\x7f"}', _file('    "a": "\\u007f"'), id="raw DEL"),
        pytest.param(
            b'{"a":"\xc0\x80"}', _file('    "a": "\\u0000"'), id="overlong NUL"
        ),
        pytest.param(
            b'{"\xc0\x80":1}', _file('    "\\u0000": 1'), id="overlong NUL in a key"
        ),
        pytest.param(b'{"a":"\xc1\x81"}', _file('    "a": "A"'), id="overlong A"),
        pytest.param(
            b'{"a":"\xe0\x80\x80"}',
            _file('    "a": "\\u0000"'),
            id="three-byte overlong NUL",
        ),
        pytest.param(
            b'{"a":"\xf0\x80\x80\x80"}',
            _file('    "a": "\\u0000"'),
            id="four-byte overlong NUL",
        ),
        pytest.param(
            b'{"a":"\xf4\x8f\xbf\xbf"}',
            _file('    "a": "\U0010ffff"'),
            id="U+10FFFF",
        ),
        pytest.param(
            b'{"a":"\xed\xa0\xbd\xed\xb8\x80"}',
            _file('    "a": "\U0001f600"'),
            id="a surrogate pair as two UTF-8 sequences",
        ),
        pytest.param(
            b'{"a":"\xed\xa0\xbdx\xed\xb8\x80"}',
            _file('    "a": "x\U0001f600"'),
            id="a UTF-8 first half, ASCII, its second half",
        ),
        pytest.param(
            b'{"a":"\xed\xa0\xbd\\udc00"}',
            _file('    "a": "\U0001f400"'),
            id="a UTF-8 first half and an escaped second half",
        ),
        pytest.param(
            b'{"a":"\\ud83d\xed\xb8\x80"}',
            _file('    "a": "\U0001f600"'),
            id="an escaped first half and a UTF-8 second half",
        ),
    ],
)
def test_a_file_is_written_back_as_core_writes_it(
    tmp_path: Path, content: str, expected: str
) -> None:
    """The bytes of every file `bitcoind` v31.1.0 rewrote from `content`."""
    assert _written(tmp_path, content) == expected


@pytest.mark.parametrize(
    "content",
    [
        pytest.param("", id="empty"),
        pytest.param(" \n", id="blank"),
        pytest.param("invalid json", id="not json"),
        pytest.param('{"a":01}', id="leading zero"),
        pytest.param('{"a":-01}', id="leading zero after a sign"),
        pytest.param('{"a":.5}', id="no integer part"),
        pytest.param('{"a":1.}', id="no fraction digit"),
        pytest.param('{"a":+1}', id="plus sign"),
        pytest.param('{"a":-}', id="sign alone"),
        pytest.param('{"a":--1}', id="two signs"),
        pytest.param('{"a":1e}', id="no exponent digit"),
        pytest.param('{"a":1e+}', id="no exponent digit after a sign"),
        pytest.param('{"a":0x1}', id="hexadecimal"),
        pytest.param('{"a":NaN}', id="NaN"),
        pytest.param('{"a":Infinity}', id="Infinity"),
        pytest.param('{"a":-Infinity}', id="negative Infinity"),
        pytest.param('{"a":t}', id="short literal"),
        pytest.param('{"a":True}', id="capital literal"),
        pytest.param('{"a":truex}', id="literal and a letter"),
        pytest.param('{"a":"x', id="unterminated string"),
        pytest.param('{"a":"\\', id="backslash at the end"),
        pytest.param('{"a":"x\ty"}', id="raw tab"),
        pytest.param('{"a":"\x01"}', id="raw control character"),
        pytest.param('{"a":"\x00"}', id="raw NUL"),
        pytest.param('{"a":"\\x"}', id="unknown escape"),
        pytest.param('{"a":"\\u12"}', id="short unicode escape"),
        pytest.param('{"a":"\\u12G4"}', id="non-hex unicode escape"),
        pytest.param('{"a":"\\u+123"}', id="signed unicode escape"),
        pytest.param('{"a":"\\ud800"}', id="a first half alone"),
        pytest.param('{"a":"\\udc00"}', id="a second half alone"),
        pytest.param('{"a":"\\ud800\\ud800"}', id="two first halves"),
        pytest.param('{"a":"\\udc00\\ud800"}', id="halves reversed"),
        pytest.param('{"a":"\\ud800\\u0041"}', id="a first half and an escape"),
        pytest.param('{"a":"\\ud800é"}', id="a first half and a raw letter"),
        pytest.param('{"a":"\\ud800\\u0041\\udc00"}', id="an escape between halves"),
        pytest.param('{"a":"\\ud800é\\udc00"}', id="a raw letter between halves"),
        pytest.param('{"\\ud800":1}', id="a first half in a key"),
        pytest.param("{'a':1}", id="single quotes"),
        pytest.param("{a:1}", id="bare key"),
        pytest.param("{1:2}", id="number key"),
        pytest.param('{"a"}', id="no colon"),
        pytest.param('{"a" 1}', id="no colon before a value"),
        pytest.param('{"a"::1}', id="two colons"),
        pytest.param('{"a":}', id="no value"),
        pytest.param('{"a":1,}', id="trailing comma"),
        pytest.param("{,}", id="lone comma"),
        pytest.param('{"a":1 "b":2}', id="no comma"),
        pytest.param('{"a":1,,"b":2}', id="two commas"),
        pytest.param('{"a":[1,]}', id="trailing comma in an array"),
        pytest.param('{"a":[,1]}', id="leading comma in an array"),
        pytest.param('{"a":[1 2]}', id="no comma in an array"),
        pytest.param('{"a":[}', id="object close in an array"),
        pytest.param('{"a":{]}', id="array close in an object"),
        pytest.param('{"a":[1}', id="array closed by an object close"),
        pytest.param('{"a":{"b":1]}', id="object closed by an array close"),
        pytest.param('{"a":]', id="array close for a value"),
        pytest.param('{"a"::}', id="colon for a value"),
        pytest.param('{"a":,}', id="comma for a value"),
        pytest.param('{"a":}', id="object close for a value"),
        pytest.param("{", id="object left open"),
        pytest.param('{"a"', id="object left open after a key"),
        pytest.param('{"a":', id="object left open after a colon"),
        pytest.param('{"a":1', id="object left open after a value"),
        pytest.param('{"a":[', id="array left open"),
        pytest.param("}", id="close first"),
        pytest.param("]", id="array close first"),
        pytest.param(":", id="colon first"),
        pytest.param(",", id="comma first"),
        pytest.param("{}{}", id="two objects"),
        pytest.param("{} {}", id="two objects apart"),
        pytest.param("{}garbage", id="trailing garbage"),
        pytest.param('{"a":1}/', id="trailing slash"),
        pytest.param("/**/{}", id="comment"),
        pytest.param("{\f}", id="form feed"),
        pytest.param("{\v}", id="vertical tab"),
        pytest.param('{"a":\u00a01}', id="no-break space"),
        pytest.param("\ufeff{}", id="byte order mark"),
        pytest.param(b"\xef\xbb\xbf{}", id="byte order mark bytes"),
        pytest.param("{}\x00", id="NUL after"),
        pytest.param("\x00{}", id="NUL before"),
        pytest.param(b'{"a":"\xff"}', id="invalid UTF-8"),
        pytest.param(b'{"a":"\xc3"}', id="truncated UTF-8"),
        pytest.param(b'{"a":"\xc3x"}', id="a continuation byte missing"),
        pytest.param(b'{"a":"\xc3\\u0041"}', id="an escape inside a sequence"),
        pytest.param(b'{"\xff":1}', id="invalid UTF-8 in a key"),
        pytest.param(b'{"a":1}\xff', id="invalid UTF-8 after"),
        pytest.param(b'{"a":"\xed\xa0\x80"}', id="a surrogate half as UTF-8"),
        pytest.param(
            b'{"a":"\xf4\x90\x80\x80"}',
            id="past U+10FFFF, which Core accepts and a str cannot hold",
        ),
        pytest.param(
            '{"a":' + "[" * 512 + "]" * 512 + "}", id="513 containers open at once"
        ),
    ],
)
def test_a_file_that_is_not_json_is_refused(
    tmp_path: Path, content: str | bytes
) -> None:
    """Each text is refused with Core's words, as `bitcoind` v31.1.0 refuses it.

    The code point past U+10FFFF is the divergence `settings_file`'s docstring
    names: Core accepts it, and a `str` cannot hold it.
    """
    assert _refusal(tmp_path, content) == (
        f"Settings file <FILE> {_INVALID}, power loss, full disk, or "
        "storage error, and can be fixed by removing the file, which will "
        "reset settings to default values."
    )


@pytest.mark.parametrize(
    "content",
    [
        pytest.param('{"a":' + "[" * 511 + "]" * 511 + "}", id="512 open at once"),
        pytest.param(
            '{"a":' + '{"a":' * 511 + "1" + "}" * 511 + "}", id="512 objects open"
        ),
    ],
)
def test_a_file_nested_512_deep_is_read_and_written(
    tmp_path: Path, content: str
) -> None:
    """Core's `MAX_JSON_DEPTH` is 512 containers, and one more is refused."""
    assert "_warning_" in _written(tmp_path, content)


@pytest.mark.parametrize(
    ("content", "shown"),
    [
        pytest.param("[1,2]", "[1,2]", id="array"),
        pytest.param('"string"', '"string"', id="string"),
        pytest.param("null", "null", id="null"),
        pytest.param("5", "5", id="number"),
        pytest.param("1.50", "1.50", id="number keeps its text"),
        pytest.param("true", "true", id="true"),
        pytest.param("false", "false", id="false"),
        pytest.param(" \t5\n", "5", id="number between blanks"),
        pytest.param("-", "-", id="a sign alone ends the text, as UniValue reads it"),
        pytest.param('[{"a":[]}]', '[{"a":[]}]', id="compact"),
        pytest.param('"\\u0001\\"/"', '"\\u0001\\"/"', id="escaped"),
    ],
)
def test_a_value_that_is_not_an_object_is_refused(
    tmp_path: Path, content: str, shown: str
) -> None:
    """The refusal writes the value compactly, as `UniValue::write` does."""
    assert _refusal(tmp_path, content) == (
        f"Found non-object value {shown} in settings file <FILE>"
    )


@pytest.mark.parametrize(
    ("content", "key"),
    [
        pytest.param('{"key": 1, "key": 2}', "key", id="plain"),
        pytest.param('{"a":1,"b":2,"a":3}', "a", id="apart"),
        pytest.param('{"":1,"":2}', "", id="empty"),
        pytest.param('{"a":1,"\\u0061":2}', "a", id="spelled differently"),
        pytest.param('{"_warning_":1,"_warning_":2}', "_warning_", id="warning"),
        pytest.param('{"x":1,"y":2,"x":3,"y":4}', "x", id="the first one named"),
    ],
)
def test_a_key_named_twice_is_refused(tmp_path: Path, content: str, key: str) -> None:
    """Only a key of the top-level object counts."""
    assert _refusal(tmp_path, content) == (
        f"Found duplicate key {key} in settings file <FILE>"
    )


def test_a_missing_file_holds_nothing(tmp_path: Path) -> None:
    """Core: "Ok for file to not exist"."""
    assert read_settings(str(tmp_path / "settings.json")) == {}


@pytest.mark.skipif(sys.platform == "win32", reason="Windows cannot open one")
def test_a_directory_is_not_valid_json(tmp_path: Path) -> None:
    """Core opens a directory and reads nothing from it."""
    path = tmp_path / "settings.json"
    path.mkdir()
    with pytest.raises(ValueError, match=_INVALID):
        read_settings(str(path))


@pytest.mark.skipif(sys.platform != "win32", reason="POSIX opens a directory")
def test_a_directory_cannot_be_opened_on_windows(  # pragma: no cover -- Windows CI only
    tmp_path: Path,
) -> None:
    """Windows refuses to open a directory, so it asks for permissions."""
    path = tmp_path / "settings.json"
    path.mkdir()
    with pytest.raises(ValueError, match=r"\. Please check permissions\.$"):
        read_settings(str(path))


@pytest.mark.skipif(
    sys.platform == "win32" or os.geteuid() == 0, reason="needs POSIX modes, not root"
)
def test_a_file_whose_status_cannot_be_read_raises_the_os_error(
    tmp_path: Path,
) -> None:
    """`fs::exists` throws on a permission error, and is false for none."""
    directory = tmp_path / "locked"
    directory.mkdir()
    (directory / "settings.json").write_text("{}", encoding="utf-8")
    directory.chmod(0)
    try:
        with pytest.raises(PermissionError):
            read_settings(str(directory / "settings.json"))
    finally:
        directory.chmod(0o700)


def test_a_path_under_a_file_holds_nothing(tmp_path: Path) -> None:
    """`ENOTDIR` is `fs::exists`'s `false` too."""
    (tmp_path / "file").write_text("", encoding="utf-8")
    assert read_settings(str(tmp_path / "file" / "settings.json")) == {}


def test_a_file_that_cannot_be_opened_asks_for_its_permissions(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A mode-0 file is no test run as root, so `open` is made to fail."""
    path = tmp_path / "settings.json"
    path.write_text("{}", encoding="utf-8")

    def refuse(*_args: object, **_kwargs: object) -> None:
        raise PermissionError

    monkeypatch.setattr("builtins.open", refuse)
    with pytest.raises(ValueError, match=r"\. Please check permissions\.$") as refused:
        read_settings(str(path))
    assert str(refused.value) == f"{path}. Please check permissions."


def test_the_values_read_are_in_key_order_without_the_warning(
    tmp_path: Path,
) -> None:
    """`std::map` holds them so, and `_warning_` is erased from it."""
    values = _read(tmp_path, '{"b":null,"_warning_":"x","a":[1],"c":{"d":2}}')
    assert list(values) == ["a", "b", "c"]
    assert values == {
        "a": [Number("1")],
        "b": None,
        "c": Object((("d", Number("2")),)),
    }


def test_a_number_is_told_from_a_string(tmp_path: Path) -> None:
    """`VNUM` and `VSTR` differ, and a number is not written in quotes."""
    values = _read(tmp_path, '{"n":5,"s":"5"}')
    assert isinstance(values["n"], Number)
    assert not isinstance(values["s"], Number)
    assert write_json(values["n"]) == "5"
    assert write_json(values["s"]) == '"5"'


@pytest.mark.parametrize(
    ("value", "name"),
    [
        (None, "null"),
        (True, "boolean"),
        (False, "boolean"),
        (Number("1"), "number"),
        ("1", "string"),
        ([], "array"),
        (Object(()), "object"),
    ],
)
def test_type_name_is_univalues(value: Json, name: str) -> None:
    """`uvTypeName`: each type is named as Core's error names it."""
    assert type_name(value) == name


def test_write_json_is_compact_unless_asked_for_an_indent() -> None:
    """`write()` and `write(4, 1)`, over one value."""
    value = Object((("a", [Number("1"), "b"]), ("c", Object(()))))
    assert write_json(value) == '{"a":[1,"b"],"c":{}}'
    assert write_json(value, indent=2) == (
        '{\n  "a": [\n    1,\n    "b"\n  ],\n  "c": {\n  }\n}'
    )


def test_write_writes_through_a_tmp_file_renamed_over_the_file(
    tmp_path: Path,
) -> None:
    """`<path>.tmp` is gone once the rename is done, and the file is whole."""
    path = tmp_path / "settings.json"
    path.write_text("old", encoding="utf-8")
    write_settings(str(path), {"a": "x"})
    assert [file.name for file in tmp_path.iterdir()] == ["settings.json"]
    assert path.read_bytes().decode("utf-8") == _file('    "a": "x"')


@pytest.mark.skipif(sys.platform == "win32", reason="Windows refuses the rename")
def test_write_replaces_a_read_only_file(tmp_path: Path) -> None:
    """The rename replaces the file whatever its mode, as `bitcoind` does."""
    path = tmp_path / "settings.json"
    path.write_text('{"a":1}', encoding="utf-8")
    path.chmod(0o444)
    write_settings(str(path), {"a": Number("1")})
    assert path.read_bytes().decode("utf-8") == _file('    "a": 1')


def test_write_replaces_a_symlink_not_its_target(tmp_path: Path) -> None:
    """Core's rename replaces the link, and leaves what it pointed at."""
    target = tmp_path / "real.json"
    target.write_text('{"a":1}', encoding="utf-8")
    link = tmp_path / "settings.json"
    link.symlink_to(target)
    write_settings(str(link), {})
    assert not link.is_symlink()
    assert target.read_text(encoding="utf-8") == '{"a":1}'


def test_write_refuses_where_the_tmp_file_cannot_be_opened(tmp_path: Path) -> None:
    """A missing directory, as for `-settings=sub/s.json` in `bitcoind`."""
    path = tmp_path / "sub" / "s.json"
    with pytest.raises(ValueError, match=r".") as refused:
        write_settings(str(path), {})
    assert str(refused.value) == (
        f"Error: Unable to open settings file {path}.tmp for writing"
    )


def test_write_refuses_where_the_tmp_name_is_a_directory(tmp_path: Path) -> None:
    """`bitcoind` v31.1.0: the same words for a directory `<file>.tmp`."""
    (tmp_path / "t.json.tmp").mkdir()
    with pytest.raises(ValueError, match="Unable to open settings file"):
        write_settings(str(tmp_path / "t.json"), {})


def test_write_refuses_a_write_that_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A full disk surfaces when the buffer is written, and the `.tmp` stays."""
    path = tmp_path / "settings.json"

    class FullDisk:
        def __enter__(self) -> Self:
            return self

        def __exit__(self, *_args: object) -> None:
            return None

        def write(self, _data: bytes) -> None:
            raise OSError

    monkeypatch.setattr("builtins.open", lambda *_a, **_k: FullDisk())
    with pytest.raises(ValueError, match=r".") as refused:
        write_settings(str(path), {})
    assert str(refused.value) == f"Error: Unable to write settings file {path}.tmp"


def test_write_refuses_a_rename_that_fails_and_leaves_the_tmp_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`ArgsManager::WriteSettingsFile`'s own words, newline included."""
    path = tmp_path / "settings.json"

    def refuse(*_args: object, **_kwargs: object) -> None:
        raise OSError

    monkeypatch.setattr("os.replace", refuse)
    with pytest.raises(ValueError, match=r".") as refused:
        write_settings(str(path), {})
    assert str(refused.value) == f"Failed renaming settings file {path}.tmp to {path}\n"
    assert (tmp_path / "settings.json.tmp").exists()
